-- Phân quyền: bảng public.phan_quyen — mỗi hàng = một cặp (chức vụ, module_key) + cột action (text) chứa nhiều quyền (khuyến nghị JSON mảng).
-- Không ràng buộc enum action trong DB để sau này thêm quyền tùy ý.
-- Tên module hiển thị: app map module_key → i18n (permission-modules-config).
-- Giữ public.he_thong_access_log (migration 514).

DROP TABLE IF EXISTS public.phan_quyen_chi_tiet CASCADE;
DROP TABLE IF EXISTS public.phan_quyen_chuc_vu_module CASCADE;
DROP TABLE IF EXISTS public.phan_quyen_module CASCADE;
DROP FUNCTION IF EXISTS public.set_phan_quyen_chuc_vu_module_tg_cap_nhat() CASCADE;
DROP TABLE IF EXISTS public.phan_quyen CASCADE;

CREATE TABLE public.phan_quyen (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_chuc_vu bigint NOT NULL REFERENCES public.chuc_vu (id) ON DELETE CASCADE,
  module_key text NOT NULL,
  action text NOT NULL DEFAULT '[]',
  tg_tao timestamptz NOT NULL DEFAULT (timezone('utc', now())),
  tg_cap_nhat timestamptz NOT NULL DEFAULT (timezone('utc', now())),
  CONSTRAINT phan_quyen_unique_cv_module UNIQUE (id_chuc_vu, module_key)
);

COMMENT ON TABLE public.phan_quyen IS 'Ma trận phân quyền: id_chuc_vu + module_key; action = text (nhiều quyền, thường là JSON array string).';
COMMENT ON COLUMN public.phan_quyen.action IS 'Text: khuyến nghị JSON array ví dụ ["view","bao_cao"]. Có thể nhập tay; app parse linh hoạt.';

CREATE INDEX idx_phan_quyen_id_chuc_vu ON public.phan_quyen USING btree (id_chuc_vu);
CREATE INDEX idx_phan_quyen_module_key ON public.phan_quyen USING btree (module_key);
CREATE INDEX idx_phan_quyen_cv_mod ON public.phan_quyen USING btree (id_chuc_vu, module_key);

CREATE OR REPLACE FUNCTION public.set_phan_quyen_tg_cap_nhat()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  NEW.tg_cap_nhat := timezone('utc', now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_phan_quyen_set_tg_cap_nhat ON public.phan_quyen;

CREATE TRIGGER trg_phan_quyen_set_tg_cap_nhat
  BEFORE UPDATE ON public.phan_quyen
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_phan_quyen_tg_cap_nhat();

ALTER TABLE public.phan_quyen ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "phan_quyen_select_authenticated" ON public.phan_quyen;
DROP POLICY IF EXISTS "phan_quyen_insert_authenticated" ON public.phan_quyen;
DROP POLICY IF EXISTS "phan_quyen_update_authenticated" ON public.phan_quyen;
DROP POLICY IF EXISTS "phan_quyen_delete_authenticated" ON public.phan_quyen;

CREATE POLICY "phan_quyen_select_authenticated"
  ON public.phan_quyen FOR SELECT TO authenticated USING (true);

CREATE POLICY "phan_quyen_insert_authenticated"
  ON public.phan_quyen FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "phan_quyen_update_authenticated"
  ON public.phan_quyen FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "phan_quyen_delete_authenticated"
  ON public.phan_quyen FOR DELETE TO authenticated USING (true);

DROP TABLE IF EXISTS public.he_thong_phan_quyen CASCADE;
